"""empty message

Revision ID: 272752d5cbbf
Revises: e1c335b1e0ac
Create Date: 2018-12-30 19:23:15.942911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272752d5cbbf'
down_revision = 'e1c335b1e0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action_State_Model',
    sa.Column('Acst_id', sa.Integer(), nullable=False),
    sa.Column('Act_id_from', sa.Integer(), nullable=True),
    sa.Column('Act_id_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Acst_id')
    )
    op.drop_constraint('Action_Act_id_to_fkey', 'Action', type_='foreignkey')
    op.drop_column('Action', 'Act_id_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('Act_id_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Action_Act_id_to_fkey', 'Action', 'Action', ['Act_id_to'], ['Act_id'])
    op.drop_table('Action_State_Model')
    # ### end Alembic commands ###
