"""empty message

Revision ID: 2944a3ef305e
Revises: 852648571a3c
Create Date: 2018-12-27 14:05:08.087030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2944a3ef305e'
down_revision = '852648571a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Issues', sa.Column('Issue_Assigned_To', sa.Integer(), nullable=True))
    op.add_column('Issues', sa.Column('Issue_Created_By', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Issues', 'Employees', ['Issue_Assigned_To'], ['Emp_id'])
    op.create_foreign_key(None, 'Issues', 'Employees', ['Issue_Created_By'], ['Emp_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_constraint(None, 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'Issue_Created_By')
    op.drop_column('Issues', 'Issue_Assigned_To')
    # ### end Alembic commands ###
