"""empty message

Revision ID: 8cd4dc0e4356
Revises: 272752d5cbbf
Create Date: 2018-12-31 11:20:52.857458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd4dc0e4356'
down_revision = '272752d5cbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Action_State_Model', 'Action', ['Act_id_from'], ['Act_id'])
    op.create_foreign_key(None, 'Action_State_Model', 'Action', ['Act_id_to'], ['Act_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Action_State_Model', type_='foreignkey')
    op.drop_constraint(None, 'Action_State_Model', type_='foreignkey')
    # ### end Alembic commands ###
