"""empty message

Revision ID: 8d20dd324ed3
Revises: 8ce44b89eedd
Create Date: 2018-11-23 22:14:33.121767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d20dd324ed3'
down_revision = '8ce44b89eedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action',
    sa.Column('Act_id', sa.Integer(), nullable=False),
    sa.Column('Act_id_to', sa.Integer(), nullable=True),
    sa.Column('Act_Is_Final', sa.Boolean(), nullable=True),
    sa.Column('Act_Name', sa.String(), nullable=True),
    sa.Column('Act_Desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Act_id_to'], ['Action.Act_id'], ),
    sa.PrimaryKeyConstraint('Act_id')
    )
    op.create_table('Customers',
    sa.Column('Cust_id', sa.Integer(), nullable=False),
    sa.Column('Cust_Created', sa.Date(), nullable=True),
    sa.Column('Cust_First_Name', sa.String(), nullable=True),
    sa.Column('Cust_Last_Name', sa.String(), nullable=True),
    sa.Column('Cust_Address_Name', sa.String(), nullable=True),
    sa.Column('Cust_Email', sa.String(), nullable=True),
    sa.Column('Cust_Contact_Num', sa.String(), nullable=True),
    sa.Column('Cust_Birth_Date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Cust_id')
    )
    op.create_table('Devices',
    sa.Column('Dev_id', sa.Integer(), nullable=False),
    sa.Column('Dev_Creator', sa.Date(), nullable=True),
    sa.Column('Dev_Manufacturer', sa.String(), nullable=True),
    sa.Column('Dev_Model', sa.String(), nullable=True),
    sa.Column('Dev_Model_Year', sa.Date(), nullable=True),
    sa.Column('Dev_Identifier_Code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Dev_id')
    )
    op.create_table('Employees',
    sa.Column('Emp_id', sa.Integer(), nullable=False),
    sa.Column('Emp_Created', sa.Date(), nullable=True),
    sa.Column('Emp_First_Name', sa.String(), nullable=True),
    sa.Column('Emp_Last_Name', sa.String(), nullable=True),
    sa.Column('Emp_Address_Name', sa.String(), nullable=True),
    sa.Column('Emp_Address_Num', sa.Integer(), nullable=True),
    sa.Column('Emp_Email', sa.String(), nullable=True),
    sa.Column('Emp_Contact_Num', sa.Integer(), nullable=True),
    sa.Column('Emp_Contact_Num2', sa.Integer(), nullable=True),
    sa.Column('Emp_Username', sa.String(), nullable=True),
    sa.Column('Emp_Password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Emp_id')
    )
    op.create_table('Inventory',
    sa.Column('Inv_id', sa.Integer(), nullable=False),
    sa.Column('Inv_Item_Name', sa.String(), nullable=True),
    sa.Column('Inv_Item_Desc', sa.String(), nullable=True),
    sa.Column('Inv_Item_Price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Inv_id')
    )
    op.create_table('Problems',
    sa.Column('Prob_id', sa.Integer(), nullable=False),
    sa.Column('Prob_Name', sa.String(), nullable=True),
    sa.Column('Prob_Desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Prob_id')
    )
    op.create_table('Roles',
    sa.Column('Role_id', sa.Integer(), nullable=False),
    sa.Column('Role_Name', sa.String(), nullable=True),
    sa.Column('Role_Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Role_id')
    )
    op.create_table('State',
    sa.Column('Stat_id', sa.Integer(), nullable=False),
    sa.Column('Stat_Name', sa.String(), nullable=True),
    sa.Column('Stat_Desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Stat_id')
    )
    op.create_table('Action_Inventory',
    sa.Column('Act_Inv_id', sa.Integer(), nullable=False),
    sa.Column('Act_id', sa.Integer(), nullable=True),
    sa.Column('Inv_id', sa.Integer(), nullable=True),
    sa.Column('Inv_Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Act_id'], ['Action.Act_id'], ),
    sa.ForeignKeyConstraint(['Inv_id'], ['Inventory.Inv_id'], ),
    sa.PrimaryKeyConstraint('Act_Inv_id')
    )
    op.create_table('Emp_Roles',
    sa.Column('Emp_Role_id', sa.Integer(), nullable=False),
    sa.Column('Emp_id', sa.Integer(), nullable=True),
    sa.Column('Role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['Employees.Emp_id'], ),
    sa.ForeignKeyConstraint(['Role_id'], ['Roles.Role_id'], ),
    sa.PrimaryKeyConstraint('Emp_Role_id')
    )
    op.create_table('Employees_logins',
    sa.Column('Emp_Logins_id', sa.Integer(), nullable=False),
    sa.Column('Emp_id', sa.Integer(), nullable=True),
    sa.Column('Emp_Logged_In', sa.Date(), nullable=True),
    sa.Column('Emp_Logged_Out', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['Employees.Emp_id'], ),
    sa.PrimaryKeyConstraint('Emp_Logins_id')
    )
    op.create_table('Issue_Timeline',
    sa.Column('Ist_id', sa.Integer(), nullable=False),
    sa.Column('Issue_id', sa.Integer(), nullable=True),
    sa.Column('Emp_id', sa.Integer(), nullable=True),
    sa.Column('Act_id', sa.Integer(), nullable=True),
    sa.Column('Ist_Created', sa.Date(), nullable=True),
    sa.Column('Ist_Comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Act_id'], ['Action.Act_id'], ),
    sa.ForeignKeyConstraint(['Emp_id'], ['Employees.Emp_id'], ),
    sa.PrimaryKeyConstraint('Ist_id')
    )
    op.create_table('Issues',
    sa.Column('Issue_id', sa.Integer(), nullable=False),
    sa.Column('Dev_id', sa.Integer(), nullable=True),
    sa.Column('Cust_id', sa.Integer(), nullable=True),
    sa.Column('Stat_id', sa.Integer(), nullable=True),
    sa.Column('Prob_id', sa.Integer(), nullable=True),
    sa.Column('Act_id', sa.Integer(), nullable=True),
    sa.Column('Issue_Created', sa.Date(), nullable=True),
    sa.Column('Issue_Closed', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Act_id'], ['Action.Act_id'], ),
    sa.ForeignKeyConstraint(['Cust_id'], ['Customers.Cust_id'], ),
    sa.ForeignKeyConstraint(['Dev_id'], ['Devices.Dev_id'], ),
    sa.ForeignKeyConstraint(['Prob_id'], ['Problems.Prob_id'], ),
    sa.ForeignKeyConstraint(['Stat_id'], ['State.Stat_id'], ),
    sa.PrimaryKeyConstraint('Issue_id')
    )
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.drop_table('Issues')
    op.drop_table('Issue_Timeline')
    op.drop_table('Employees_logins')
    op.drop_table('Emp_Roles')
    op.drop_table('Action_Inventory')
    op.drop_table('State')
    op.drop_table('Roles')
    op.drop_table('Problems')
    op.drop_table('Inventory')
    op.drop_table('Employees')
    op.drop_table('Devices')
    op.drop_table('Customers')
    op.drop_table('Action')
    # ### end Alembic commands ###
