"""empty message

Revision ID: c8cac1c6776d
Revises: 8d20dd324ed3
Create Date: 2018-11-25 17:43:28.228421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cac1c6776d'
down_revision = '8d20dd324ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('Emp_Comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Employees', 'Emp_Comments')
    # ### end Alembic commands ###
