"""empty message

Revision ID: d590ad313a55
Revises: eb5922876c5e
Create Date: 2018-11-30 22:04:12.312715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd590ad313a55'
down_revision = 'eb5922876c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('Cust_Contact_Num_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customers', 'Cust_Contact_Num_2')
    # ### end Alembic commands ###
