"""empty message

Revision ID: e1c335b1e0ac
Revises: 2944a3ef305e
Create Date: 2018-12-30 13:46:19.784569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c335b1e0ac'
down_revision = '2944a3ef305e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Issues', sa.Column('Issue_Delivery_At', sa.String(), nullable=True))
    op.add_column('Issues', sa.Column('Issue_Track_Num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Issues', 'Issue_Track_Num')
    op.drop_column('Issues', 'Issue_Delivery_At')
    # ### end Alembic commands ###
