"""empty message

Revision ID: e6047eb3a998
Revises: f4506f36abcc
Create Date: 2018-12-23 16:55:42.848999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6047eb3a998'
down_revision = 'f4506f36abcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('Issues_Act_id_fkey', 'Issues', type_='foreignkey')
    #op.drop_column('Issues', 'Act_id')    
    op.drop_constraint('Issues_Act_id_fkey', 'Issues', type_='foreignkey')
    op.drop_column('Issues', 'Act_id')
    op.create_foreign_key('Issue_Timeline_Iss_id_fkey', 'Issue_Timeline', 'Issues', ['Issue_id'], ['Issue_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('Issues', sa.Column('Act_id', sa.INTEGER(), autoincrement=False, nullable=True))
    #op.create_foreign_key('Issues_Act_id_fkey', 'Issues', 'Action', ['Act_id'], ['Act_id'])
    op.add_column('Issues', sa.Column('Act_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Issues_Act_id_fkey', 'Issues', 'Action', ['Act_id'], ['Act_id'])
    op.drop_constraint('Issue_Timeline_Iss_id_fkey', 'Issue_Timeline', type_='foreignkey')
    # ### end Alembic commands ###
