"""empty message

Revision ID: eb5922876c5e
Revises: c8cac1c6776d
Create Date: 2018-11-25 18:48:42.576965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5922876c5e'
down_revision = 'c8cac1c6776d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Employees', 'Emp_Comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('Emp_Comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
